### ISSUE TITLE
tailwindcss update

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/web-app-fundamentals#12]
![app-scrollbar](https://user-images.githubusercontent.com/3650909/229033756-84fa75a5-39be-40fd-b764-3f89219cb205.png)

- While `kcdshop` is using `scrollbar plugin for tailwind css` [(tailwind-scrollbar)](https://www.npmjs.com/package/tailwind-scrollbar) `web-app-fundamentals` does not using it, as well as `rocket-rental`.

-  Tailwind CSS v3.3.1 is out [(releases page on GitHub)](https://github.com/tailwindlabs/tailwindcss/releases)
  `@tailwindcss/line-clamp` in now in core.
    ```
    As of Tailwind CSS v3.3, the `@tailwindcss/line-clamp` plugin is now included by default.
    Remove it from the `plugins` array in your configuration to eliminate this warning.
    ```

Would you like me to open a PR for these issues?

**Comment by kentcdodds** [comment]
I think that would be great 👍
