### ISSUE TITLE
Speed-up seed time by reducing the number of cities

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/web-app-fundamentals#6]
Most of the seeding time `spend` on creating 6013 cities.

🌱 Seeding...
🧹 Cleaned up the database...: 363.853ms
🌃 Created 6013 cities...: 36.977s
......
🌱 Database has been seeded: 49.395s

You can save 30 seconds by reducing the number of cities.

```diff
	const citiesToCreate = allTheCities
-		.filter(c => c.population > 75_000)
+		.filter(c => c.population > 750_000)
		.sort((a, z) => z.population - a.population)
	console.timeEnd('🧹 filter allTheCities')
```

This is the seed result for cities after the filter changed:
🌃 Created 494 cities...: 2.732s
🌱 Database has been seeded: 15.377s

**Comment by kentcdodds** [comment]
Good point! We don't even really use that data in this workshop anyway, so having a lot of them doesn't make sense.
